### ISSUE TITLE
Swift Test -> inline frames 

### ISSUE THREAD

**Issue by HazAT** [bitstadium/CrashProbe#7]
Since everybody has to redo their tests now (https://github.com/bitstadium/CrashProbe/pull/6), can we also discuss the result of the Swift test (probably in another issue)?

Referencing the previous discussion between @anlinde @mitsuhiko bitstadium/CrashProbe-Data#15 (comment)
https://github.com/bitstadium/CrashProbe-Data/blob/master/ios/22/_sentry_arm64.crash#L12

Just wanted to get the opinion of other contributors about the issue, since we still think our result is not incomplete it shows more information. The result that we propose is matching what lldb/xcode and other systems do (eg: show inlined frame information).

**Comment by mitsuhiko** [comment]
To make this clearer we propose to change the expected result from 

```
@objc CrashLibiOS.CRLCrashSwift.crash (CrashLibiOS.CRLCrashSwift)() -> () (CRLCrashSwift.swift:36)
-[CRLDetailViewController doCrash] (CRLDetailViewController.m:53)
```

to something like this:

```
[inlined] CRLCrashSwift.crash() -> () (CRLCrashSwift.swift:36)
@objc CRLCrashSwift.crash() -> ()
-[CRLDetailViewController doCrash] (CRLDetailViewController.m:53)
```

**Comment by anlinde** [comment]
So here is the link to the previous discussion with my arguments: https://github.com/bitstadium/CrashProbe-Data/pull/15/files/6030317b7cc5adcbe4eadf2641b3dac2f7f3a6c1#r109227117

Some thoughts:
- I still stand by that point, showing two frames with the same address per se is confusing.
- Just because LLDB shows inline frames isn't an argument for me that this is the way it is supposed to be shown, because this actually is an implementation detail on Apples end. You could also say with the same argument why doesn't Apple ever show any inline frames in their own crash reports then? Isn't that right?
- I do not agree to change the expected behaviour to only be correct if it shows inline frames
- We can have an argument wether your suggested expected results is a valid second presentation in that scenario. But disagree it being the only one.

@gwynne Do you want to chime in?

**Comment by mitsuhiko** [comment]
May I just ask for some clarifications:

> because this actually is an implementation detail on Apples end.

Can you clarify what you mean by implementation detail?

The reason we are showing inlined frames is largely unrelated to swift but because compiler optimizations are otherwise destroying useful bits of the stacktrace. The information in which we expand inline frames is stored in the DWARF format and we do not special case anything here. If we were not to expand inline frames we would run at risk that higher optimization levels might group differently because the compiler might decide to inline a function.

> We can have an argument wether your suggested expected results is a valid second presentation in that scenario. But disagree it being the only one.

I'm not suggesting that this would become the canonical form anyways, just permissible :)

**Comment by anlinde** [comment]
Sorry for the late response :(

In this example, the apps code in `-[CRLDetailViewController doCrash]` directly calls `CrashLibiOS.CRLCrashSwift.crash` from a developers point of view. This inline frame basically is the internal implementation in the runtime to bridge from Swift to Objective-C. It doesn't give the developer anything important that is mandatory to be shown. That's just my opinion.

Your explanation why you are expanding inline frames sounds good to me (even though we decided against it as we haven't seen real cases where this is of help and not more confusion in most other cases).

Would you be fine with my suggestion to say both are valid and correct?

**Comment by mitsuhiko** [comment]
> Would you be fine with my suggestion to say both are valid and correct?

Yeah. No objections there.

**Comment by HazAT** [comment]
I think we can close this.
Thank you
